analytics:
  twitter: null
  facebook: null
  google: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2185821
  lightness: 0.7384533
  brandStrength: 0.5912997
  brandColors:
    - '#FFFFFF'
    - '#1E201F'
    - '#C7BCA5'
    - '#766E5C'
    - '#FF7743'
  rhythmicContrast: 0.9264232
typography_spectrum: 0.03813101
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.9479054
favicon: null
name: HarleyToday
