layout_spectrum: 0.9612142
favicon: null
name: HarleyToday
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  bucket: null
  version: null
  domain: null
color:
  brandStrength: 0.955312
  saturation: 0.9548244923353195
  brandColors:
    - '#80776E'
    - '#BDBEC5'
    - '#0F0B0D'
    - '#EBE8E8'
    - '#BE906E'
  lightness: 0.201006441609934
  rhythmicContrast: 0.4586146825458854
typography_spectrum: 0
