cta:
  version: null
  bucket: null
  domain: null
name: HarleyToday
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
typography_spectrum: 0.2545179761946201
color:
  saturation: 0.9548244923353195
  brandStrength: 0.4688507
  lightness: 0.201006441609934
  brandColors:
    - '#80776E'
    - '#BDBEC5'
    - '#0F0B0D'
    - '#EBE8E8'
    - '#BE906E'
  rhythmicContrast: 0.4586146825458854
layout_spectrum: 0.9612142
analytics:
  twitter: null
  facebook: null
  google: null
favicon: null
