analytics:
  twitter: null
  facebook: null
  google: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.7180451
  lightness: 0.7384533
  brandStrength: 0.679377
  brandColors:
    - '#0176BC'
    - '#D7E0EB'
    - '#384C65'
    - '#6EA4DF'
    - '#15150E'
  rhythmicContrast: 1
typography_spectrum: 0.03813101
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.9479054
favicon: null
name: HarleyToday
