name: HarleyToday
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.9548245
  lightness: 0.2010064
  brandStrength: 0.2851772
  brandColors:
    - '#80776E'
    - '#BDBEC5'
    - '#0F0B0D'
    - '#EBE8E8'
    - '#BE906E'
  rhythmicContrast: 0
typography_spectrum: 0.03813101
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.9479054
favicon: null
analytics:
  twitter: null
  facebook: null
  google: null
