name: HarleyToday
favicon: null
layout_spectrum: 0.8879948130343109
typography_spectrum: 0.25451797619462013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.029461876256391406
  lightness: 0.20100644160993397
  saturation: 0.9548244923353195
  rhythmicContrast: 0.45861468254588544
purpose: []
