favicon: null
name: HarleyToday
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4709989
  brandStrength: 0.2851772
  lightness: 0.2010064
  brandColors:
    - '#80776E'
    - '#BDBEC5'
    - '#0F0B0D'
    - '#EBE8E8'
    - '#BE906E'
  rhythmicContrast: 0.1380236
typography_spectrum: 0.03813101
layout_spectrum: 0.9479054
analytics:
  twitter: null
  facebook: null
  google: null
cta:
  version: null
  bucket: null
  domain: null
